"use client";

import { useCallback, useEffect, useState } from "react";
import { Download, Film, RefreshCw, Sparkles } from "lucide-react";
import { useI18n } from "@/components/i18n-provider";
import type { PublicConversationVideo } from "@/lib/memoir/workflow";

export function MemoirVideoCard({
  sessionId,
  initialVideo,
}: {
  sessionId: string;
  initialVideo: PublicConversationVideo | null;
}) {
  const { locale } = useI18n();
  const chinese = locale !== "en";
  const [video, setVideo] = useState(initialVideo);
  const [starting, setStarting] = useState(false);
  const [requestError, setRequestError] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    if (!video || video.status === "ready" || video.status === "failed") return;
    try {
      const response = await fetch(`/api/family/conversation-videos/${video.id}`, {
        cache: "no-store",
      });
      const body = await response.json();
      if (!response.ok) throw new Error(body.error ?? "Could not refresh the video.");
      setVideo(body.video);
    } catch (error) {
      setRequestError(error instanceof Error ? error.message : "Could not refresh the video.");
    }
  }, [video]);

  useEffect(() => {
    if (!video || video.status === "ready" || video.status === "failed") return;
    const timer = window.setInterval(() => void refresh(), 15_000);
    return () => window.clearInterval(timer);
  }, [refresh, video]);

  async function start(regenerate = false) {
    const confirmed = window.confirm(
      regenerate
        ? chinese
          ? "这将替换当前短片，并根据原始对话重新生成整个短片。可能会产生费用。要继续吗？"
          : "This will replace the current film and regenerate the entire video from the original conversation. This may incur a charge. Continue?"
        : chinese
          ? "这将使用 SeeGen 制作画面，并以独立的 AI 旁白创作一部约两分钟的动画短片。生成可能会产生费用。要继续吗？"
          : "This will use SeeGen for the visuals and a separate AI narrator to create an approximately two-minute animated film. Generation may incur a charge. Continue?",
    );
    if (!confirmed) return;
    setStarting(true);
    setRequestError(null);
    setVideo((current) => current ?? {
      id: "preparing",
      status: "planning",
      title: null,
      durationMs: null,
      error: null,
      videoUrl: null,
      clips: [],
      createdAt: new Date().toISOString(),
    });
    try {
      const response = await fetch("/api/family/conversation-videos", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sessionId, regenerate }),
      });
      const body = await response.json();
      if (!response.ok) throw new Error(body.error ?? "Could not start the video.");
      setVideo(body.video);
    } catch (error) {
      setVideo(initialVideo);
      setRequestError(error instanceof Error ? error.message : "Could not start the video.");
    } finally {
      setStarting(false);
    }
  }

  const active = video && ["planning", "preparing", "generating", "rendering"].includes(video.status);
  const progressMessage = video?.status === "planning" || video?.status === "preparing"
    ? chinese ? "正在将您的故事写成 SeeGen 动画脚本……" : "Writing your story as a SeeGen animation script…"
    : video?.status === "rendering"
      ? chinese ? "正在剪辑测试短片……" : "Editing your test film…"
      : chinese ? "正在绘制动画场景。这可能需要一些时间，您可以稍后再回来。" : "Animating the scene. This can take a while—you may safely come back later.";

  return (
    <section className="rounded-2xl border border-line bg-cream p-6 shadow-sm" aria-labelledby="memoir-video-title">
      <div className="flex items-start gap-4">
        <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-ember/10 text-ember">
          <Film className="h-6 w-6" aria-hidden="true" />
        </div>
        <div className="min-w-0 flex-1">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-ember">
            {chinese ? "动画回忆" : "Animated memoir"}
          </p>
          <h2 id="memoir-video-title" className="mt-1 font-serif text-2xl font-semibold">
            {video?.title || (chinese ? "把这个故事变成一部短片" : "Turn this story into a short film")}
          </h2>
          <p className="mt-2 max-w-2xl text-sm leading-6 text-ink-soft">
            {chinese
              ? "AI 会把您讲述的完整故事改编成一部约两分钟的动画回忆。SeeGen 生成无声画面，独立的 AI 讲述者提供连贯旁白；不会使用或模仿您的声音。"
              : "AI will adapt the complete story you told into an approximately two-minute animated memoir. SeeGen creates silent visuals, while a separate AI storyteller provides one continuous narration track. It will not use or imitate your voice."}
          </p>
          <p className="mt-2 text-xs text-ink-faint">
            {chinese ? "画面由 SeeGen 生成；您听到的讲述者是 AI 合成声音，并非真人录音。" : "Visuals are generated by SeeGen. The narrator you hear is an AI-generated voice, not a human recording."}
          </p>
        </div>
      </div>

      {video?.status === "ready" && video.videoUrl ? (
        <div className="mt-6 space-y-4">
          <video
            className="aspect-video w-full rounded-xl bg-black shadow-inner"
            controls
            preload="metadata"
            src={video.videoUrl}
          >
            {chinese ? "您的浏览器无法播放此视频。" : "Your browser cannot play this video."}
          </video>
          <div className="flex flex-wrap gap-3">
            <a
              className="inline-flex items-center gap-2 rounded-lg bg-ember-deep px-4 py-2 font-semibold text-cream shadow-sm transition-colors hover:bg-ink"
              href={video.videoUrl}
              download={`${video.title || "animated-memoir"}.mp4`}
            >
              <Download className="h-4 w-4" aria-hidden="true" />
              {chinese ? "下载短片" : "Download film"}
            </a>
            <button
              className="inline-flex items-center gap-2 rounded-lg bg-ember px-4 py-2 font-semibold text-cream shadow-sm transition-colors hover:bg-ember-deep disabled:opacity-60"
              type="button"
              onClick={() => void start(true)}
              disabled={starting}
            >
              <RefreshCw className="h-4 w-4" aria-hidden="true" />
              {chinese ? "重新生成短片" : "Regenerate video"}
            </button>
          </div>
        </div>
      ) : active ? (
        <div className="mt-6 rounded-xl bg-paper p-5" role="status" aria-live="polite">
          <div className="flex items-center gap-3">
            <RefreshCw className="h-5 w-5 animate-spin text-ember" aria-hidden="true" />
            <p className="font-medium text-ink">{progressMessage}</p>
          </div>
        </div>
      ) : (
        <div className="mt-6">
          <button
            className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-ember px-5 py-3 font-semibold text-cream transition-colors hover:bg-ember-deep disabled:opacity-60"
            type="button"
            onClick={() => void start(false)}
            disabled={starting}
          >
            <Sparkles className="h-5 w-5" aria-hidden="true" />
            {video?.status === "failed"
              ? chinese ? "再试一次" : "Try creating it again"
              : chinese ? "创作动画短片" : "Create animated film"}
          </button>
        </div>
      )}

      {video?.clips.length ? (
        <div className="mt-6">
          <div className="flex items-end justify-between gap-4">
            <div>
              <h3 className="font-serif text-xl font-semibold text-ink">
                {chinese ? "已保存的动画场景" : "Saved animation scenes"}
              </h3>
              <p className="mt-1 text-sm text-ink-soft">
                {chinese
                  ? `已安全保存 ${video.clips.length} 个场景。`
                  : `${video.clips.length} scenes are safely saved with this conversation.`}
              </p>
            </div>
          </div>
          <div className="mt-4 grid gap-4 sm:grid-cols-2">
            {video.clips.map((clip) => (
              <div className="overflow-hidden rounded-xl border border-ink/15 bg-ink shadow-sm" key={clip.sceneNumber}>
                <video
                  className="aspect-video w-full bg-black"
                  controls
                  preload="metadata"
                  src={clip.videoUrl}
                >
                  {chinese ? "您的浏览器无法播放此视频。" : "Your browser cannot play this video."}
                </video>
                <div className="flex items-center justify-between gap-3 px-4 py-3">
                  <span className="text-sm font-medium text-cream">
                    {chinese ? `场景 ${clip.sceneNumber}` : `Scene ${clip.sceneNumber}`}
                  </span>
                  <a
                    className="inline-flex items-center gap-1.5 rounded-md bg-ember px-3 py-1.5 text-sm font-semibold text-cream transition-colors hover:bg-ember-deep"
                    href={clip.videoUrl}
                    download={`scene-${clip.sceneNumber}.mp4`}
                  >
                    <Download className="h-4 w-4" aria-hidden="true" />
                    {chinese ? "下载" : "Download"}
                  </a>
                </div>
              </div>
            ))}
          </div>
        </div>
      ) : null}

      {(requestError || video?.error) ? (
        <p className="mt-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">
          {requestError || video?.error}
        </p>
      ) : null}
    </section>
  );
}
