"use client";

import { useCallback, useEffect, useState } from "react";
import { Download, Film, RefreshCw, Sparkles } from "lucide-react";
import { useI18n } from "@/components/i18n-provider";
import type { PublicConversationVideo } from "@/lib/memoir/workflow";
import type { Locale } from "@/lib/i18n";

const copyByLocale: Record<Locale, {
  refreshError: string;
  startError: string;
  confirmRegenerate: string;
  confirmStart: string;
  planning: string;
  rendering: string;
  generating: string;
  kicker: string;
  title: string;
  body: string;
  disclosure: string;
  unsupported: string;
  downloadFilm: string;
  regenerate: string;
  retry: string;
  create: string;
  savedScenes: string;
  scenesSaved: (count: number) => string;
  scene: (number: number) => string;
  download: string;
  regenerateScene: string;
  regeneratingScene: string;
  confirmRegenerateScene: (number: number) => string;
  sceneError: string;
}> = {
  en: {
    refreshError: "Could not refresh the video.", startError: "Could not start the video.",
    confirmRegenerate: "This will replace the current film and regenerate the entire video from the original conversation. This may incur a charge. Continue?",
    confirmStart: "This will use SeeGen for the visuals and a separate AI narrator to create a 90-second to two-minute animated film. Generation may incur a charge. Continue?",
    planning: "Writing your story as a SeeGen animation script…", rendering: "Editing your test film…",
    generating: "Animating the scene. This can take a while—you may safely come back later.",
    kicker: "Animated memoir", title: "Turn this story into a short film",
    body: "AI will adapt the complete story you told into a 90-second to two-minute animated memoir. SeeGen creates silent visuals, while a separate AI storyteller provides one continuous narration track. It will not use or imitate your voice.",
    disclosure: "Visuals are generated by SeeGen. The narrator you hear is an AI-generated voice, not a human recording.",
    unsupported: "Your browser cannot play this video.", downloadFilm: "Download film", regenerate: "Regenerate video",
    retry: "Try creating it again", create: "Create animated film", savedScenes: "Saved animation scenes",
    scenesSaved: (count) => `${count} scenes are safely saved with this conversation.`,
    scene: (number) => `Scene ${number}`, download: "Download", regenerateScene: "Regenerate",
    regeneratingScene: "Regenerating…",
    confirmRegenerateScene: (number) => `Regenerate scene ${number}? This will replace only this scene and may incur a charge.`,
    sceneError: "Could not regenerate the scene.",
  },
  "zh-Hans": {
    refreshError: "无法刷新视频。", startError: "无法开始生成视频。",
    confirmRegenerate: "这将替换当前短片，并根据原始对话重新生成整个短片。可能会产生费用。要继续吗？",
    confirmStart: "这将使用 SeeGen 制作画面，并以独立的 AI 旁白创作一部约一分半至两分钟的动画短片。生成可能会产生费用。要继续吗？",
    planning: "正在将您的故事写成 SeeGen 动画脚本……", rendering: "正在剪辑测试短片……",
    generating: "正在绘制动画场景。这可能需要一些时间，您可以稍后再回来。",
    kicker: "动画回忆", title: "把这个故事变成一部短片",
    body: "AI 会把您讲述的完整故事改编成一部约一分半至两分钟的动画回忆。SeeGen 生成无声画面，独立的 AI 讲述者提供连贯旁白；不会使用或模仿您的声音。",
    disclosure: "画面由 SeeGen 生成；您听到的讲述者是 AI 合成声音，并非真人录音。",
    unsupported: "您的浏览器无法播放此视频。", downloadFilm: "下载短片", regenerate: "重新生成短片",
    retry: "再试一次", create: "创作动画短片", savedScenes: "已保存的动画场景",
    scenesSaved: (count) => `已安全保存 ${count} 个场景。`, scene: (number) => `场景 ${number}`, download: "下载", regenerateScene: "重新生成",
    regeneratingScene: "正在重新生成…",
    confirmRegenerateScene: (number) => `要重新生成场景 ${number} 吗？这只会替换此场景，并可能产生费用。`,
    sceneError: "无法重新生成场景。",
  },
  "zh-Hant": {
    refreshError: "無法重新整理影片。", startError: "無法開始生成影片。",
    confirmRegenerate: "這將取代目前的短片，並根據原始對話重新生成整部短片。可能會產生費用。要繼續嗎？",
    confirmStart: "這將使用 SeeGen 製作畫面，並以獨立的 AI 旁白創作一部約一分半至兩分鐘的動畫短片。生成可能會產生費用。要繼續嗎？",
    planning: "正在將您的故事寫成 SeeGen 動畫腳本……", rendering: "正在剪輯測試短片……",
    generating: "正在繪製動畫場景。這可能需要一些時間，您可以稍後再回來。",
    kicker: "動畫回憶", title: "把這個故事變成一部短片",
    body: "AI 會把您講述的完整故事改編成一部約一分半至兩分鐘的動畫回憶。SeeGen 生成無聲畫面，獨立的 AI 講述者提供連貫旁白；不會使用或模仿您的聲音。",
    disclosure: "畫面由 SeeGen 生成；您聽到的講述者是 AI 合成聲音，並非真人錄音。",
    unsupported: "您的瀏覽器無法播放此影片。", downloadFilm: "下載短片", regenerate: "重新生成短片",
    retry: "再試一次", create: "創作動畫短片", savedScenes: "已儲存的動畫場景",
    scenesSaved: (count) => `已安全儲存 ${count} 個場景。`, scene: (number) => `場景 ${number}`, download: "下載", regenerateScene: "重新生成",
    regeneratingScene: "正在重新生成…",
    confirmRegenerateScene: (number) => `要重新生成場景 ${number} 嗎？這只會取代此場景，並可能產生費用。`,
    sceneError: "無法重新生成場景。",
  },
};

export function MemoirVideoCard({
  sessionId,
  initialVideo,
}: {
  sessionId: string;
  initialVideo: PublicConversationVideo | null;
}) {
  const { locale } = useI18n();
  const copy = copyByLocale[locale];
  const [video, setVideo] = useState(initialVideo);
  const [starting, setStarting] = useState(false);
  const [regeneratingScene, setRegeneratingScene] = useState<number | null>(null);
  const [requestError, setRequestError] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    if (!video || video.status === "ready" || video.status === "failed") return;
    try {
      const response = await fetch(`/api/family/conversation-videos/${video.id}`, {
        cache: "no-store",
      });
      const body = await response.json();
      if (!response.ok) throw new Error(locale === "en" ? body.error ?? copy.refreshError : copy.refreshError);
      setVideo(body.video);
    } catch (error) {
      setRequestError(error instanceof Error ? error.message : copy.refreshError);
    }
  }, [copy.refreshError, locale, video]);

  useEffect(() => {
    if (!video || video.status === "ready" || video.status === "failed") return;
    const timer = window.setInterval(() => void refresh(), 15_000);
    return () => window.clearInterval(timer);
  }, [refresh, video]);

  async function start(regenerate = false) {
    const confirmed = window.confirm(
      regenerate ? copy.confirmRegenerate : copy.confirmStart,
    );
    if (!confirmed) return;
    setStarting(true);
    setRequestError(null);
    setVideo((current) => current ?? {
      id: "preparing",
      status: "planning",
      title: null,
      durationMs: null,
      error: null,
      videoUrl: null,
      clips: [],
      createdAt: new Date().toISOString(),
    });
    try {
      const response = await fetch("/api/family/conversation-videos", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sessionId, regenerate }),
      });
      const body = await response.json();
      if (!response.ok) throw new Error(locale === "en" ? body.error ?? copy.startError : copy.startError);
      setVideo(body.video);
    } catch (error) {
      setVideo(initialVideo);
      setRequestError(error instanceof Error ? error.message : copy.startError);
    } finally {
      setStarting(false);
    }
  }

  async function regenerateScene(sceneNumber: number) {
    if (!video || !window.confirm(copy.confirmRegenerateScene(sceneNumber))) return;
    setRegeneratingScene(sceneNumber);
    setRequestError(null);
    try {
      const response = await fetch(
        `/api/family/conversation-videos/${video.id}/scenes/${sceneNumber}`,
        { method: "POST" },
      );
      const body = await response.json();
      if (!response.ok) {
        throw new Error(locale === "en" ? body.error ?? copy.sceneError : copy.sceneError);
      }
      setVideo(body.video);
    } catch (error) {
      setRequestError(error instanceof Error ? error.message : copy.sceneError);
    } finally {
      setRegeneratingScene(null);
    }
  }

  const active = video && ["planning", "preparing", "generating", "rendering"].includes(video.status);
  const progressMessage = video?.status === "planning" || video?.status === "preparing"
    ? copy.planning
    : video?.status === "rendering"
      ? copy.rendering
      : copy.generating;

  return (
    <section className="rounded-2xl border border-line bg-cream p-6 shadow-sm" aria-labelledby="memoir-video-title">
      <div className="flex items-start gap-4">
        <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-ember/10 text-ember">
          <Film className="h-6 w-6" aria-hidden="true" />
        </div>
        <div className="min-w-0 flex-1">
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-ember">
            {copy.kicker}
          </p>
          <h2 id="memoir-video-title" className="mt-1 font-serif text-2xl font-semibold">
            {video?.title || copy.title}
          </h2>
          <p className="mt-2 max-w-2xl text-sm leading-6 text-ink-soft">
            {copy.body}
          </p>
          <p className="mt-2 text-xs text-ink-faint">
            {copy.disclosure}
          </p>
        </div>
      </div>

      {video?.status === "ready" && video.videoUrl ? (
        <div className="mt-6 space-y-4">
          <video
            className="aspect-video w-full rounded-xl bg-black shadow-inner"
            controls
            preload="metadata"
            src={video.videoUrl}
          >
            {copy.unsupported}
          </video>
          <div className="flex flex-wrap gap-3">
            <a
              className="inline-flex items-center gap-2 rounded-lg bg-ember-deep px-4 py-2 font-semibold text-cream shadow-sm transition-colors hover:bg-ink"
              href={video.videoUrl}
              download={`${video.title || "animated-memoir"}.mp4`}
            >
              <Download className="h-4 w-4" aria-hidden="true" />
              {copy.downloadFilm}
            </a>
            <button
              className="inline-flex items-center gap-2 rounded-lg bg-ember px-4 py-2 font-semibold text-cream shadow-sm transition-colors hover:bg-ember-deep disabled:opacity-60"
              type="button"
              onClick={() => void start(true)}
              disabled={starting}
            >
              <RefreshCw className="h-4 w-4" aria-hidden="true" />
              {copy.regenerate}
            </button>
          </div>
        </div>
      ) : active ? (
        <div className="mt-6 rounded-xl bg-paper p-5" role="status" aria-live="polite">
          <div className="flex items-center gap-3">
            <RefreshCw className="h-5 w-5 animate-spin text-ember" aria-hidden="true" />
            <p className="font-medium text-ink">{progressMessage}</p>
          </div>
        </div>
      ) : (
        <div className="mt-6">
          <button
            className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-ember px-5 py-3 font-semibold text-cream transition-colors hover:bg-ember-deep disabled:opacity-60"
            type="button"
            onClick={() => void start(false)}
            disabled={starting}
          >
            <Sparkles className="h-5 w-5" aria-hidden="true" />
            {video?.status === "failed" ? copy.retry : copy.create}
          </button>
        </div>
      )}

      {video?.clips.length ? (
        <div className="mt-6">
          <div className="flex items-end justify-between gap-4">
            <div>
              <h3 className="font-serif text-xl font-semibold text-ink">
                {copy.savedScenes}
              </h3>
              <p className="mt-1 text-sm text-ink-soft">
                {copy.scenesSaved(video.clips.length)}
              </p>
            </div>
          </div>
          <div className="mt-4 grid gap-4 sm:grid-cols-2">
            {video.clips.map((clip) => (
              <div className="overflow-hidden rounded-xl border border-ink/15 bg-ink shadow-sm" key={clip.sceneNumber}>
                <video
                  className="aspect-video w-full bg-black"
                  controls
                  preload="metadata"
                  src={clip.videoUrl}
                >
                  {copy.unsupported}
                </video>
                <div className="flex items-center justify-between gap-3 px-4 py-3">
                  <span className="text-sm font-medium text-cream">
                    {copy.scene(clip.sceneNumber)}
                  </span>
                  <div className="flex flex-wrap items-center justify-end gap-2">
                    <a
                      className="inline-flex items-center gap-1.5 rounded-md bg-ember px-3 py-1.5 text-sm font-semibold text-cream transition-colors hover:bg-ember-deep"
                      href={clip.videoUrl}
                      download={`scene-${clip.sceneNumber}.mp4`}
                    >
                      <Download className="h-4 w-4" aria-hidden="true" />
                      {copy.download}
                    </a>
                    <button
                      className="inline-flex items-center gap-1.5 rounded-md border border-cream/30 bg-cream/10 px-3 py-1.5 text-sm font-semibold text-cream transition-colors hover:bg-cream/20 disabled:cursor-not-allowed disabled:opacity-55"
                      type="button"
                      onClick={() => void regenerateScene(clip.sceneNumber)}
                      disabled={starting || regeneratingScene !== null || video.status !== "ready"}
                    >
                      <RefreshCw
                        className={`h-4 w-4 ${regeneratingScene === clip.sceneNumber ? "animate-spin" : ""}`}
                        aria-hidden="true"
                      />
                      {regeneratingScene === clip.sceneNumber || video.status !== "ready"
                        ? copy.regeneratingScene
                        : copy.regenerateScene}
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      ) : null}

      {(requestError || video?.error) ? (
        <p className="mt-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">
          {requestError || video?.error}
        </p>
      ) : null}
    </section>
  );
}
