import "server-only";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type GeneratedEmailLink = {
  hashed_token?: string | null;
  verification_type?: string | null;
};

/**
 * Turns a link generated by Supabase Admin into the cookie-backed session used
 * by the app. A "magiclink" request for a new email can come back as a
 * "signup" verification link, so the returned verification type must be used
 * instead of assuming it matches the requested link type.
 */
export async function verifyGeneratedEmailLink(link: GeneratedEmailLink) {
  const type =
    link.verification_type === "signup" ||
    link.verification_type === "magiclink"
      ? link.verification_type
      : null;

  if (!link.hashed_token || !type) {
    return {
      ok: false as const,
      error: new Error("Supabase returned an unsupported email-link type."),
    };
  }

  const supabase = await createSupabaseServerClient();
  const { error } = await supabase.auth.verifyOtp({
    token_hash: link.hashed_token,
    type,
  });

  if (error) {
    return { ok: false as const, error };
  }

  return { ok: true as const };
}
